hiragana_name = [
    "Hiragana_A", "Hiragana_Ba", "Hiragana_Be", "Hiragana_Bi", "Hiragana_Bo", "Hiragana_Bu", "Hiragana_Bya",
    "Hiragana_Byo", "Hiragana_Byu", "Hiragana_Cha", "Hiragana_Chi", "Hiragana_Cho", "Hiragana_Chu", "Hiragana_Da",
    "Hiragana_De", "Hiragana_Do", "Hiragana_E", "Hiragana_Fu", "Hiragana_Ga", "Hiragana_Ge", "Hiragana_Gi",
    "Hiragana_Go", "Hiragana_Gu", "Hiragana_Gya", "Hiragana_Gyo", "Hiragana_Gyu", "Hiragana_Ha", "Hiragana_He",
    "Hiragana_Hi", "Hiragana_Ho", "Hiragana_Hya", "Hiragana_Hyo", "Hiragana_Hyu", "Hiragana_I", "Hiragana_Ja",
    "Hiragana_Ji", "Hiragana_Ji_2", "Hiragana_Jo", "Hiragana_Ju", "Hiragana_Ka", "Hiragana_Ke", "Hiragana_Ki",
    "Hiragana_Ko", "Hiragana_Ku", "Hiragana_Kya", "Hiragana_Kyo", "Hiragana_Kyu", "Hiragana_Ma", "Hiragana_Me",
    "Hiragana_Mi", "Hiragana_Mo", "Hiragana_Mu", "Hiragana_Mya", "Hiragana_Myo", "Hiragana_Myu", "Hiragana_N",
    "Hiragana_Na", "Hiragana_Ne", "Hiragana_Ni", "Hiragana_No", "Hiragana_Nu", "Hiragana_Nya", "Hiragana_Nyo",
    "Hiragana_Nyu", "Hiragana_O", "Hiragana_Pa", "Hiragana_Pe", "Hiragana_Pi", "Hiragana_Po", "Hiragana_Pu",
    "Hiragana_Pya", "Hiragana_Pyo", "Hiragana_Pyu", "Hiragana_Ra", "Hiragana_Re", "Hiragana_Ri", "Hiragana_Ro",
    "Hiragana_Ru", "Hiragana_Rya", "Hiragana_Ryo", "Hiragana_Ryu", "Hiragana_Sa", "Hiragana_Se", "Hiragana_Sha",
    "Hiragana_Shi", "Hiragana_Sho", "Hiragana_Shu", "Hiragana_So", "Hiragana_Su", "Hiragana_Ta", "Hiragana_Te",
    "Hiragana_To", "Hiragana_Tsu", "Hiragana_U", "Hiragana_Wa", "Hiragana_Wo", "Hiragana_Ya", "Hiragana_Yo",
    "Hiragana_Yu", "Hiragana_Za", "Hiragana_Ze", "Hiragana_Zo", "Hiragana_Zu", "Hiragana_Zu_2"
]

katakana_name = [
    "Katakana_A", "Katakana_Ba", "Katakana_Be", "Katakana_Bi", "Katakana_Bo", "Katakana_Bu", "Katakana_Bya",
    "Katakana_Byo", "Katakana_Byu", "Katakana_Cha", "Katakana_Che", "Katakana_Chi", "Katakana_Cho", "Katakana_Chu",
    "Katakana_Da", "Katakana_De", "Katakana_Di", "Katakana_Do", "Katakana_Du", "Katakana_Dyu", "Katakana_E",
    "Katakana_Fa", "Katakana_Fe", "Katakana_Fi", "Katakana_Fo", "Katakana_Fu", "Katakana_Ga", "Katakana_Ge",
    "Katakana_Gi", "Katakana_Go", "Katakana_Gu", "Katakana_Gya", "Katakana_Gyo", "Katakana_Gyu", "Katakana_Ha",
    "Katakana_He", "Katakana_Hi", "Katakana_Ho", "Katakana_Hya", "Katakana_Hyo", "Katakana_Hyu", "Katakana_I",
    "Katakana_Ja", "Katakana_Je", "Katakana_Ji", "Katakana_Ji_2", "Katakana_Jo", "Katakana_Ju", "Katakana_Ka",
    "Katakana_Ke", "Katakana_Ki", "Katakana_Ko", "Katakana_Ku", "Katakana_Kya", "Katakana_Kyo", "Katakana_Kyu",
    "Katakana_Ma", "Katakana_Me", "Katakana_Mi", "Katakana_Mo", "Katakana_Mu", "Katakana_Mya", "Katakana_Myo",
    "Katakana_Myu", "Katakana_N", "Katakana_Na", "Katakana_Ne", "Katakana_Ni", "Katakana_No", "Katakana_Nu",
    "Katakana_Nya", "Katakana_Nyo", "Katakana_Nyu", "Katakana_O", "Katakana_Pa", "Katakana_Pe", "Katakana_Pi",
    "Katakana_Po", "Katakana_Pu", "Katakana_Pya", "Katakana_Pyo", "Katakana_Pyu", "Katakana_Ra", "Katakana_Re",
    "Katakana_Ri", "Katakana_Ro", "Katakana_Ru", "Katakana_Rya", "Katakana_Ryo", "Katakana_Ryu", "Katakana_Sa",
    "Katakana_Se", "Katakana_Sha", "Katakana_She", "Katakana_Shi", "Katakana_Sho", "Katakana_Shu", "Katakana_So",
    "Katakana_Su", "Katakana_Ta", "Katakana_Te", "Katakana_Ti", "Katakana_To", "Katakana_Tsa", "Katakana_Tse",
    "Katakana_Tso", "Katakana_Tsu", "Katakana_Tu", "Katakana_U", "Katakana_Wa", "Katakana_We", "Katakana_Wi",
    "Katakana_Wo", "Katakana_Wo_2", "Katakana_Ya", "Katakana_Yo", "Katakana_Yu", "Katakana_Za", "Katakana_Ze",
    "Katakana_Zo", "Katakana_Zu", "Katakana_Zu_2"
]

hiragana_label = [
    [0, "A"],
    [1, "Ba"],
    [2, "Be"],
    [3, "Bi"],
    [4, "Bo"],
    [5, "Bu"],
    [6, "Bya"],
    [7, "Byo"],
    [8, "Byu"],
    [9, "Cha"],
    [10, "Chi"],
    [11, "Cho"],
    [12, "Chu"],
    [13, "Da"],
    [14, "De"],
    [15, "Do"],
    [16, "E"],
    [17, "Fu"],
    [18, "Ga"],
    [19, "Ge"],
    [20, "Gi"],
    [21, "Go"],
    [22, "Gu"],
    [23, "Gya"],
    [24, "Gyo"],
    [25, "Gyu"],
    [26, "Ha"],
    [27, "He"],
    [28, "Hi"],
    [29, "Ho"],
    [30, "Hya"],
    [31, "Hyo"],
    [32, "Hyu"],
    [33, "I"],
    [34, "Ja"],
    [35, "Ji"],
    [36, "Ji"],
    [37, "Jo"],
    [38, "Ju"],
    [39, "Ka"],
    [40, "Ke"],
    [41, "Ki"],
    [42, "Ko"],
    [43, "Ku"],
    [44, "Kya"],
    [45, "Kyo"],
    [46, "Kyu"],
    [47, "Ma"],
    [48, "Me"],
    [49, "Mi"],
    [50, "Mo"],
    [51, "Mu"],
    [52, "Mya"],
    [53, "Myo"],
    [54, "Myu"],
    [55, "N"],
    [56, "Na"],
    [57, "Ne"],
    [58, "Ni"],
    [59, "No"],
    [60, "Nu"],
    [61, "Nya"],
    [62, "Nyo"],
    [63, "Nyu"],
    [64, "O"],
    [65, "Pa"],
    [66, "Pe"],
    [67, "Pi"],
    [68, "Po"],
    [69, "Pu"],
    [70, "Pya"],
    [71, "Pyo"],
    [72, "Pyu"],
    [73, "Ra"],
    [74, "Re"],
    [75, "Ri"],
    [76, "Ro"],
    [77, "Ru"],
    [78, "Rya"],
    [79, "Ryo"],
    [80, "Ryu"],
    [81, "Sa"],
    [82, "Se"],
    [83, "Sha"],
    [84, "Shi"],
    [85, "Sho"],
    [86, "Shu"],
    [87, "So"],
    [88, "Su"],
    [89, "Ta"],
    [90, "Te"],
    [91, "To"],
    [92, "Tsu"],
    [93, "U"],
    [94, "Wa"],
    [95, "Wo"],
    [96, "Ya"],
    [97, "Yo"],
    [98, "Yu"],
    [99, "Za"],
    [100, "Ze"],
    [101, "Zo"],
    [102, "Zu"],
    [103, "Zu"]
]

katakana_label = [
    [104, "A"],
    [105, "Ba"],
    [106, "Be"],
    [107, "Bi"],
    [108, "Bo"],
    [109, "Bu"],
    [110, "Bya"],
    [111, "Byo"],
    [112, "Byu"],
    [113, "Cha"],
    [114, "Che"],
    [115, "Chi"],
    [116, "Cho"],
    [117, "Chu"],
    [118, "Da"],
    [119, "De"],
    [120, "Di"],
    [121, "Do"],
    [122, "Du"],
    [123, "Dyu"],
    [124, "E"],
    [125, "Fa"],
    [126, "Fe"],
    [127, "Fi"],
    [128, "Fo"],
    [129, "Fu"],
    [130, "Ga"],
    [131, "Ge"],
    [132, "Gi"],
    [133, "Go"],
    [134, "Gu"],
    [135, "Gya"],
    [136, "Gyo"],
    [137, "Gyu"],
    [138, "Ha"],
    [139, "He"],
    [140, "Hi"],
    [141, "Ho"],
    [142, "Hya"],
    [143, "Hyo"],
    [144, "Hyu"],
    [145, "I"],
    [146, "Ja"],
    [147, "Je"],
    [148, "Ji"],
    [149, "Ji"],
    [150, "Jo"],
    [151, "Ju"],
    [152, "Ka"],
    [153, "Ke"],
    [154, "Ki"],
    [155, "Ko"],
    [156, "Ku"],
    [157, "Kya"],
    [158, "Kyo"],
    [159, "Kyu"],
    [160, "Ma"],
    [161, "Me"],
    [162, "Mi"],
    [163, "Mo"],
    [164, "Mu"],
    [165, "Mya"],
    [166, "Myo"],
    [167, "Myu"],
    [168, "N"],
    [169, "Na"],
    [170, "Ne"],
    [171, "Ni"],
    [172, "No"],
    [173, "Nu"],
    [174, "Nya"],
    [175, "Nyo"],
    [176, "Nyu"],
    [177, "O"],
    [178, "Pa"],
    [179, "Pe"],
    [180, "Pi"],
    [181, "Po"],
    [182, "Pu"],
    [183, "Pya"],
    [184, "Pyo"],
    [185, "Pyu"],
    [186, "Ra"],
    [187, "Re"],
    [188, "Ri"],
    [189, "Ro"],
    [190, "Ru"],
    [191, "Rya"],
    [192, "Ryo"],
    [193, "Ryu"],
    [194, "Sa"],
    [195, "Se"],
    [196, "Sha"],
    [197, "She"],
    [198, "Shi"],
    [199, "Sho"],
    [200, "Shu"],
    [201, "So"],
    [202, "Su"],
    [203, "Ta"],
    [204, "Te"],
    [205, "Ti"],
    [206, "To"],
    [207, "Tsa"],
    [208, "Tse"],
    [209, "Tso"],
    [210, "Tsu"],
    [211, "Tu"],
    [212, "U"],
    [213, "Wa"],
    [214, "We"],
    [215, "Wi"],
    [216, "Wo"],
    [217, "Wo"],
    [218, "Ya"],
    [219, "Yo"],
    [220, "Yu"],
    [221, "Za"],
    [222, "Ze"],
    [223, "Zo"],
    [224, "Zu"],
    [225, "Zu"]
]
