hiragana_name = [
    "Hiragana_A", "Hiragana_Ba", "Hiragana_Be", "Hiragana_Bi", "Hiragana_Bo", "Hiragana_Bu", "Hiragana_Bya",
    "Hiragana_Byo", "Hiragana_Byu", "Hiragana_Cha", "Hiragana_Chi", "Hiragana_Cho", "Hiragana_Chu", "Hiragana_Da",
    "Hiragana_De", "Hiragana_Do", "Hiragana_E", "Hiragana_Fu", "Hiragana_Ga", "Hiragana_Ge", "Hiragana_Gi",
    "Hiragana_Go", "Hiragana_Gu", "Hiragana_Gya", "Hiragana_Gyo", "Hiragana_Gyu", "Hiragana_Ha", "Hiragana_He",
    "Hiragana_Hi", "Hiragana_Ho", "Hiragana_Hya", "Hiragana_Hyo", "Hiragana_Hyu", "Hiragana_I", "Hiragana_Ja",
    "Hiragana_Ji", "Hiragana_Ji_2", "Hiragana_Jo", "Hiragana_Ju", "Hiragana_Ka", "Hiragana_Ke", "Hiragana_Ki",
    "Hiragana_Ko", "Hiragana_Ku", "Hiragana_Kya", "Hiragana_Kyo", "Hiragana_Kyu", "Hiragana_Ma", "Hiragana_Me",
    "Hiragana_Mi", "Hiragana_Mo", "Hiragana_Mu", "Hiragana_Mya", "Hiragana_Myo", "Hiragana_Myu", "Hiragana_N",
    "Hiragana_Na", "Hiragana_Ne", "Hiragana_Ni", "Hiragana_No", "Hiragana_Nu", "Hiragana_Nya", "Hiragana_Nyo",
    "Hiragana_Nyu", "Hiragana_O", "Hiragana_Pa", "Hiragana_Pe", "Hiragana_Pi", "Hiragana_Po", "Hiragana_Pu",
    "Hiragana_Pya", "Hiragana_Pyo", "Hiragana_Pyu", "Hiragana_Ra", "Hiragana_Re", "Hiragana_Ri", "Hiragana_Ro",
    "Hiragana_Ru", "Hiragana_Rya", "Hiragana_Ryo", "Hiragana_Ryu", "Hiragana_Sa", "Hiragana_Se", "Hiragana_Sha",
    "Hiragana_Shi", "Hiragana_Sho", "Hiragana_Shu", "Hiragana_So", "Hiragana_Su", "Hiragana_Ta", "Hiragana_Te",
    "Hiragana_To", "Hiragana_Tsu", "Hiragana_U", "Hiragana_Wa", "Hiragana_Wo", "Hiragana_Ya", "Hiragana_Yo",
    "Hiragana_Yu", "Hiragana_Za", "Hiragana_Ze", "Hiragana_Zo", "Hiragana_Zu", "Hiragana_Zu_2"
]

katakana_name = [
    "Katakana_A", "Katakana_Ba", "Katakana_Be", "Katakana_Bi", "Katakana_Bo", "Katakana_Bu", "Katakana_Bya",
    "Katakana_Byo", "Katakana_Byu", "Katakana_Cha", "Katakana_Che", "Katakana_Chi", "Katakana_Cho", "Katakana_Chu",
    "Katakana_Da", "Katakana_De", "Katakana_Di", "Katakana_Do", "Katakana_Du", "Katakana_Dyu", "Katakana_E",
    "Katakana_Fa", "Katakana_Fe", "Katakana_Fi", "Katakana_Fo", "Katakana_Fu", "Katakana_Ga", "Katakana_Ge",
    "Katakana_Gi", "Katakana_Go", "Katakana_Gu", "Katakana_Gya", "Katakana_Gyo", "Katakana_Gyu", "Katakana_Ha",
    "Katakana_He", "Katakana_Hi", "Katakana_Ho", "Katakana_Hya", "Katakana_Hyo", "Katakana_Hyu", "Katakana_I",
    "Katakana_Ja", "Katakana_Je", "Katakana_Ji", "Katakana_Ji_2", "Katakana_Jo", "Katakana_Ju", "Katakana_Ka",
    "Katakana_Ke", "Katakana_Ki", "Katakana_Ko", "Katakana_Ku", "Katakana_Kya", "Katakana_Kyo", "Katakana_Kyu",
    "Katakana_Ma", "Katakana_Me", "Katakana_Mi", "Katakana_Mo", "Katakana_Mu", "Katakana_Mya", "Katakana_Myo",
    "Katakana_Myu", "Katakana_N", "Katakana_Na", "Katakana_Ne", "Katakana_Ni", "Katakana_No", "Katakana_Nu",
    "Katakana_Nya", "Katakana_Nyo", "Katakana_Nyu", "Katakana_O", "Katakana_Pa", "Katakana_Pe", "Katakana_Pi",
    "Katakana_Po", "Katakana_Pu", "Katakana_Pya", "Katakana_Pyo", "Katakana_Pyu", "Katakana_Ra", "Katakana_Re",
    "Katakana_Ri", "Katakana_Ro", "Katakana_Ru", "Katakana_Rya", "Katakana_Ryo", "Katakana_Ryu", "Katakana_Sa",
    "Katakana_Se", "Katakana_Sha", "Katakana_She", "Katakana_Shi", "Katakana_Sho", "Katakana_Shu", "Katakana_So",
    "Katakana_Su", "Katakana_Ta", "Katakana_Te", "Katakana_Ti", "Katakana_To", "Katakana_Tsa", "Katakana_Tse",
    "Katakana_Tso", "Katakana_Tsu", "Katakana_Tu", "Katakana_U", "Katakana_Wa", "Katakana_We", "Katakana_Wi",
    "Katakana_Wo", "Katakana_Wo_2", "Katakana_Ya", "Katakana_Yo", "Katakana_Yu", "Katakana_Za", "Katakana_Ze",
    "Katakana_Zo", "Katakana_Zu", "Katakana_Zu_2"
]

hiragana_label = [
    [0, "A", "A"], [1, "Ba", "Ba"], [2, "Be", "Be"], [3, "Bi", "Bi"], [4, "Bo", "Bo"], [5, "Bu", "Bu"],
    [6, "Bya", "Bya"], [7, "Byo", "Byo"], [8, "Byu", "Byu"], [9, "Cha", "Cha"], [10, "Chi", "Chi"], [11, "Cho", "Cho"],
    [12, "Chu", "Chu"], [13, "Da", "Da"], [14, "De", "De"], [15, "Do", "Do"], [16, "E", "E"], [17, "Fu", "Fu"],
    [18, "Ga", "Ga"], [19, "Ge", "Ge"], [20, "Gi", "Gi"], [21, "Go", "Go"], [22, "Gu", "Gu"], [23, "Gya", "Gya"],
    [24, "Gyo", "Gyo"], [25, "Gyu", "Gyu"], [26, "Ha", "Ha"], [27, "He", "He"], [28, "Hi", "Hi"], [29, "Ho", "Ho"],
    [30, "Hya", "Hya"], [31, "Hyo", "Hyo"], [32, "Hyu", "Hyu"], [33, "I", "I"], [34, "Ja", "Ja"], [35, "Ji", "Ji"],
    [36, "Ji_2", "Ji"], [37, "Jo", "Jo"], [38, "Ju", "Ju"], [39, "Ka", "Ka"], [40, "Ke", "Ke"], [41, "Ki", "Ki"],
    [42, "Ko", "Ko"], [43, "Ku", "Ku"], [44, "Kya", "Kya"], [45, "Kyo", "Kyo"], [46, "Kyu", "Kyu"], [47, "Ma", "Ma"],
    [48, "Me", "Me"], [49, "Mi", "Mi"], [50, "Mo", "Mo"], [51, "Mu", "Mu"], [52, "Mya", "Mya"], [53, "Myo", "Myo"],
    [54, "Myu", "Myu"], [55, "N", "N"], [56, "Na", "Na"], [57, "Ne", "Ne"], [58, "Ni", "Ni"], [59, "No", "No"],
    [60, "Nu", "Nu"], [61, "Nya", "Nya"], [62, "Nyo", "Nyo"], [63, "Nyu", "Nyu"], [64, "O", "O"], [65, "Pa", "Pa"],
    [66, "Pe", "Pe"], [67, "Pi", "Pi"], [68, "Po", "Po"], [69, "Pu", "Pu"], [70, "Pya", "Pya"], [71, "Pyo", "Pyo"],
    [72, "Pyu", "Pyu"], [73, "Ra", "Ra"], [74, "Re", "Re"], [75, "Ri", "Ri"], [76, "Ro", "Ro"], [77, "Ru", "Ru"],
    [78, "Rya", "Rya"], [79, "Ryo", "Ryo"], [80, "Ryu", "Ryu"], [81, "Sa", "Sa"], [82, "Se", "Se"], [83, "Sha", "Sha"],
    [84, "Shi", "Shi"], [85, "Sho", "Sho"], [86, "Shu", "Shu"], [87, "So", "So"], [88, "Su", "Su"], [89, "Ta", "Ta"],
    [90, "Te", "Te"], [91, "To", "To"], [92, "Tsu", "Tsu"], [93, "U", "U"], [94, "Wa", "Wa"], [95, "Wo", "Wo"],
    [96, "Ya", "Ya"], [97, "Yo", "Yo"], [98, "Yu", "Yu"], [99, "Za", "Za"], [100, "Ze", "Ze"], [101, "Zo", "Zo"],
    [102, "Zu", "Zu"], [103, "Zu_2", "Zu"]
]

katakana_label = [
    [104, "A", "A"], [105, "Ba", "Ba"], [106, "Be", "Be"], [107, "Bi", "Bi"], [108, "Bo", "Bo"], [109, "Bu", "Bu"],
    [110, "Bya", "Bya"], [111, "Byo", "Byo"], [112, "Byu", "Byu"], [113, "Cha", "Cha"], [114, "Che", "Che"],
    [115, "Chi", "Chi"], [116, "Cho", "Cho"], [117, "Chu", "Chu"], [118, "Da", "Da"], [119, "De", "De"],
    [120, "Di", "Di"], [121, "Do", "Do"], [122, "Du", "Du"], [123, "Dyu", "Dyu"], [124, "E", "E"], [125, "Fa", "Fa"],
    [126, "Fe", "Fe"], [127, "Fi", "Fi"], [128, "Fo", "Fo"], [129, "Fu", "Fu"], [130, "Ga", "Ga"], [131, "Ge", "Ge"],
    [132, "Gi", "Gi"], [133, "Go", "Go"], [134, "Gu", "Gu"], [135, "Gya", "Gya"], [136, "Gyo", "Gyo"],
    [137, "Gyu", "Gyu"], [138, "Ha", "Ha"], [139, "He", "He"], [140, "Hi", "Hi"], [141, "Ho", "Ho"],
    [142, "Hya", "Hya"], [143, "Hyo", "Hyo"], [144, "Hyu", "Hyu"], [145, "I", "I"], [146, "Ja", "Ja"],
    [147, "Je", "Je"], [148, "Ji", "Ji"], [149, "Ji_2", "Ji"], [150, "Jo", "Jo"], [151, "Ju", "Ju"], [152, "Ka", "Ka"],
    [153, "Ke", "Ke"], [154, "Ki", "Ki"], [155, "Ko", "Ko"], [156, "Ku", "Ku"], [157, "Kya", "Kya"],
    [158, "Kyo", "Kyo"], [159, "Kyu", "Kyu"], [160, "Ma", "Ma"], [161, "Me", "Me"], [162, "Mi", "Mi"],
    [163, "Mo", "Mo"], [164, "Mu", "Mu"], [165, "Mya", "Mya"], [166, "Myo", "Myo"], [167, "Myu", "Myu"],
    [168, "N", "N"], [169, "Na", "Na"], [170, "Ne", "Ne"], [171, "Ni", "Ni"], [172, "No", "No"], [173, "Nu", "Nu"],
    [174, "Nya", "Nya"], [175, "Nyo", "Nyo"], [176, "Nyu", "Nyu"], [177, "O", "O"], [178, "Pa", "Pa"],
    [179, "Pe", "Pe"], [180, "Pi", "Pi"], [181, "Po", "Po"], [182, "Pu", "Pu"], [183, "Pya", "Pya"],
    [184, "Pyo", "Pyo"], [185, "Pyu", "Pyu"], [186, "Ra", "Ra"], [187, "Re", "Re"], [188, "Ri", "Ri"],
    [189, "Ro", "Ro"], [190, "Ru", "Ru"], [191, "Rya", "Rya"], [192, "Ryo", "Ryo"], [193, "Ryu", "Ryu"],
    [194, "Sa", "Sa"], [195, "Se", "Se"], [196, "Sha", "Sha"], [197, "She", "She"], [198, "Shi", "Shi"],
    [199, "Sho", "Sho"], [200, "Shu", "Shu"], [201, "So", "So"], [202, "Su", "Su"], [203, "Ta", "Ta"],
    [204, "Te", "Te"], [205, "Ti", "Ti"], [206, "To", "To"], [207, "Tsa", "Tsa"], [208, "Tse", "Tse"],
    [209, "Tso", "Tso"], [210, "Tsu", "Tsu"], [211, "Tu", "Tu"], [212, "U", "U"], [213, "Wa", "Wa"], [214, "We", "We"],
    [215, "Wi", "Wi"], [216, "Wo", "Wo"], [217, "Wo_2", "Wo"], [218, "Ya", "Ya"], [219, "Yo", "Yo"], [220, "Yu", "Yu"],
    [221, "Za", "Za"], [222, "Ze", "Ze"], [223, "Zo", "Zo"], [224, "Zu", "Zu"], [225, "Zu_2", "Zu"]
]
